package manifest

import _ "embed"

// manifestGz is generated by tools/genmanifest from the vendored spec.
// Regenerate with `make generate`; CI fails when it drifts from the spec.
//
//go:embed manifest.json.gz
var manifestGz []byte

// Load parses the manifest embedded in this binary.
func Load() (*Manifest, error) { return Parse(manifestGz) }
